version: '2'
services:
    web:
        build: .
        command: bash -c "python manage.py migrate --no-input && python manage.py runserver 0.0.0.0:8000"
        env_file:
            - .env
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres:9.6
        restart: always
        volumes:
            - "./volumes/db:/var/lib/postgresql/data"