# Generated by Django 2.2.6 on 2019-10-03 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_score_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='scored_by',
        ),
    ]
