# Generated by Django 2.2.6 on 2019-10-03 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_score_scored_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='profesor',
            new_name='professor',
        ),
    ]
