# Generated by Django 2.2.6 on 2019-10-03 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191003_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='professor',
            new_name='professor_id',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='student',
            new_name='student_id',
        ),
    ]
